package com.deepsea.models;

public class Vessel {
    private int vesselId;
    private String name;
    private int berthCapacity;
    private int maxDepth;
    private String status;

    // Constructor for creating a new Vessel (ID is generated by database)
    public Vessel(String name, int berthCapacity, int maxDepth, String status) {
        this.name = name;
        this.berthCapacity = berthCapacity;
        this.maxDepth = maxDepth;
        this.status = status;
    }

    // Constructor for reading a Vessel from the database (includes ID)
    public Vessel(int vesselId, String name, int berthCapacity, int maxDepth, String status) {
        this.vesselId = vesselId;
        this.name = name;
        this.berthCapacity = berthCapacity;
        this.maxDepth = maxDepth;
        this.status = status;
    }

    // Getters
    public int getVesselId() { return vesselId; }
    public String getName() { return name; }
    public int getBerthCapacity() { return berthCapacity; }
    public int getMaxDepth() { return maxDepth; }
    public String getStatus() { return status; }

    @Override
    public String toString() {
        return "Vessel [ID=" + vesselId + ", Name=" + name + ", Status=" + status + "]";
    }
}